"use server";

import { getSpotifyClient } from "@/lib/spotify-client";
import { fisherYatesShuffle } from "@/lib/algorithms/fisher-yates";

export async function createShufflePlaylist(sourcePlaylistId: string, sourceName: string) {
  const spotify = await getSpotifyClient();

  if (!spotify) {
    throw new Error("Unauthorized");
  }

  try {
    // 1. Determine Target Name
    // Rule: If source already ends with " - Alter", keep it. Else append " - Alter".
    const suffix = " - Alter";
    const targetName = sourceName.endsWith(suffix) ? sourceName : `${sourceName}${suffix}`;

    // 2. Fetch ALL tracks from Source (Handle Pagination)
    let allTracks: string[] = [];
    let offset = 0;
    let keepFetching = true;

    while (keepFetching) {
      const response = await spotify.getPlaylistTracks(sourcePlaylistId, {
        limit: 100,
        offset: offset,
        fields: "items(track(uri)),total,next",
      });

      const items = response.body.items;
      const uris = items
        .map((item) => item.track?.uri)
        .filter((uri): uri is string => typeof uri === "string" && uri.startsWith("spotify:track:"));

      allTracks = [...allTracks, ...uris];

      if (response.body.next) {
        offset += 100;
      } else {
        keepFetching = false;
      }
    }

    if (allTracks.length === 0) {
      return { success: false, message: "No tracks found in this playlist." };
    }

    // 3. Shuffle Tracks
    const shuffledTracks = fisherYatesShuffle(allTracks);

    // 4. Check if Target Playlist Exists (to avoid duplicates)
    // We fetch user playlists and look for a name match.
    // Note: This fetches top 50 playlists. If user has more, we might miss it (acceptable for MVP).
    const userPlaylists = await spotify.getUserPlaylists({ limit: 50 });
    const existingPlaylist = userPlaylists.body.items.find(p => p.name === targetName);

    let targetPlaylistId = existingPlaylist?.id;

    if (targetPlaylistId) {
       // UPDATE Mode
       // console.log("Updating existing playlist:", targetName);
       
       // Replace tracks. For the first 100, we use replaceTracks (PUT).
       // For the rest, we subtract from the shuffled array and add them.
       // Actually, replaceTracks replaces EVERYTHING with the inputs. 
       // So pass strictly the first chunk to replace, then add the rest.
       const firstChunk = shuffledTracks.slice(0, 100);
       await spotify.replaceTracksInPlaylist(targetPlaylistId, firstChunk);

       // Add remaining chunks
       if (shuffledTracks.length > 100) {
          const remainingTracks = shuffledTracks.slice(100);
          const chunkSize = 100;
          for (let i = 0; i < remainingTracks.length; i += chunkSize) {
            const chunk = remainingTracks.slice(i, i + chunkSize);
            await spotify.addTracksToPlaylist(targetPlaylistId, chunk);
          }
       }

    } else {
      // CREATE Mode
      // console.log("Creating new playlist:", targetName);
      const newPlaylist = await spotify.createPlaylist(
        targetName,
        {
          description: `Generated by NanoSpotify. True Random Shuffle of '${sourceName}'.`,
          public: false,
        }
      );
      targetPlaylistId = newPlaylist.body.id;

      // Add Tracks in Batches
      const chunkSize = 100;
      for (let i = 0; i < shuffledTracks.length; i += chunkSize) {
        const chunk = shuffledTracks.slice(i, i + chunkSize);
        await spotify.addTracksToPlaylist(targetPlaylistId, chunk);
      }
    }

    return { success: true, playlistId: targetPlaylistId };
  } catch (error) {
    console.error("Error creating shuffle playlist:", error);
    return { success: false, message: "Failed to create shuffle playlist." };
  }
}
