"use server";

import { getSpotifyClient } from "@/lib/spotify-client";
import { fisherYatesShuffle } from "@/lib/algorithms/fisher-yates";

export async function createShufflePlaylist(sourcePlaylistId: string, sourceName: string) {
  const spotify = await getSpotifyClient();

  if (!spotify) {
    throw new Error("Unauthorized");
  }

  try {
    // 1. Fetch ALL tracks (Handle Pagination)
    let allTracks: string[] = [];
    let offset = 0;
    let keepFetching = true;

    while (keepFetching) {
      const response = await spotify.getPlaylistTracks(sourcePlaylistId, {
        limit: 100,
        offset: offset,
        fields: "items(track(uri)),total,next",
      });

      const items = response.body.items;
      // Filter out null tracks (can happen in Spotify) and local files (no URI usually start with spotify:track)
      const uris = items
        .map((item) => item.track?.uri)
        .filter((uri): uri is string => typeof uri === "string" && uri.startsWith("spotify:track:"));

      allTracks = [...allTracks, ...uris];

      if (response.body.next) {
        offset += 100;
      } else {
        keepFetching = false;
      }
    }

    if (allTracks.length === 0) {
      return { success: false, message: "No tracks found in this playlist." };
    }

    // 2. Shuffle Tracks
    const shuffledTracks = fisherYatesShuffle(allTracks);

    // 3. Create New Playlist
    const me = await spotify.getMe();
    const newPlaylist = await spotify.createPlaylist(
      `${sourceName} 🔀 True Shuffle`,
      {
        description: `Generated by NanoSpotify. True Random Shuffle of '${sourceName}'.`,
        public: false,
      }
    );

    // 4. Add Tracks in Batches (Limit 100 per request)
    const chunkSize = 100;
    for (let i = 0; i < shuffledTracks.length; i += chunkSize) {
      const chunk = shuffledTracks.slice(i, i + chunkSize);
      await spotify.addTracksToPlaylist(newPlaylist.body.id, chunk);
    }

    return { success: true, playlistId: newPlaylist.body.id };
  } catch (error) {
    console.error("Error creating shuffle playlist:", error);
    return { success: false, message: "Failed to create shuffle playlist." };
  }
}
